version: '3.8'
services:
  frontend:
    build:
      context: ./frontEnd  # Path to the frontend Dockerfile
    ports:
      - "5002:80"         # Map frontend to localhost:5002

  backend:
    build:
      context: ./backend  # Path to the backend Dockerfile
    ports:
      - "3001:3001"       # Map backend to localhost:3001
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"     # Map MongoDB to localhost:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
